rpc_url = "ws://127.0.0.1:16110"
p2p_port = 16110
p2p_bootstrap_peers = ["127.0.0.1:16110"]

adaptive = true
base_min_delta = 1000
base_rate_limit = 60
base_reward_sompi = 100000
max_reward_sompi = 1000000
min_rate_limit = 10
dag_window = 10000
